### ISSUE TITLE
down arrow not working in inventory screen

### ISSUE THREAD

**Issue by clararaubertas** [openproduce/marzipan#45]
"Search for item" - you should be able to page thru results with the arrow keys but this is currently not working

**Comment by clararaubertas** [comment]
locally: can't find a version where this is not a problem! even "master". need to check what version is running on presumably functional machines (cardamom?)

also: hitting down arrow causes a brief "flash" of correct behavior, then resets. something is overriding it?

**Comment by clararaubertas** [comment]
going back to old versions -- cannot find working version of this at all.

**Comment by jeredw** [comment]
I may have fixed this but we should test scanning barcodes and swiping ccs. (Some multi-byte control sequences might not work now but I don't think we have any.)
